### PR TITLE
WIP: Issue 20 - Robust production of base ontologies

### PR DESCRIPTION
**Pull request by wdduncan**
The Makefile has been updated. Mainly I've rearranged the workflow. At least for me the workflow is more straightforward.   

Changes include:
1. All for multiple ontology ids to be passed to make command; e.g.: `make go cl`
2. Add targets for making all big or all small ontologies: `make all-big`, `make all-small`. I mainly used this for testing. Maybe others will find it useful.
3. Handle the creation of base modules in a python file (`util/create_base_ontology.py`), and the logic of whether a base module is created handled by a makefile conditional:
```
CHECK := ''
$(ONT_IDS): dependencies/obo_context.jsonld | dependencies
	@echo '*** target $@ ***'
	$(eval ONT_ID := $@)
	$(eval CHECK := $(strip $(filter $(ONT_ID), $(SMALL_ONT_IDS))))

## if small ontology try to get a base iri
ifneq ($(strip $(CHECK)),'')
	$(eval CREATE_BASE := $(shell python3 util/create_base_ontology.py $(ONT_ID) $<))
	@echo '$(CREATE_BASE)'
endif
	@make dashboard/$(ONT_ID)/dashboard.html
```
The logic in `util/create_base_ontology.py` implements the same logic as before, but now we can just update the program for adding more complex rules regarding base modules.  

I ran `make` for all ontologies. The output is attached in a zip file.
[index.html.zip](https://github.com/OBOFoundry/OBO-Dashboard/files/4672721/index.html.zip)

### CODE REVIEW

**Comment by jamesaoverton** [comment]
We never took time to make the old Makefile friendly, so I can see how you would want to revise it. I'm afraid that I don't really understand what's happening in this revision, though.

1. The "all*" tasks use recursive `make -e` to override variables. I've never had to use that feature before. It makes it very hard to figure out what's going to happen.
2. The "all" tasks run "db" to build `dashboard/index.html` before running the ontology tasks. After running `make clean` these seemed to run the whole build twice.
3. `.PHONY: dashboard/index.html` should not be used with a file -- files aren't PHONY
4. I've never had to use a conditional like this in a Makefile, I would just use a script:

```
CHECK := ''
$(ONT_IDS): dependencies/obo_context.jsonld | dependencies
	@echo '*** target $@ ***'
	$(eval ONT_ID := $@)
	$(eval CHECK := $(strip $(filter $(ONT_ID), $(SMALL_ONT_IDS))))

## if small ontology try to get a base iri
ifneq ($(strip $(CHECK)),'')
	$(eval CREATE_BASE := $(shell python3 util/create_base_ontology.py $(ONT_ID) $<))
	@echo '$(CREATE_BASE)'
endif
	@make dashboard/$(ONT_ID)/dashboard.html
```

5. I didn't see where `util/download_file.py` was called, or why it's needed.

**Comment by wdduncan** [comment]
@jamesaoverton Sorry you don't understand the features I used. I found the old version quite incomprehensible. Since I was tasked with doing this, I had to put it into a form I can understand and modify easily.

conditionals:
https://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html

make -e:
‘-e’
‘--environment-overrides’
Give variables taken from the environment precedence over variables from makefiles. See Variables from the Environment.

**Comment by wdduncan** [comment]
@jamesaoverton 
Sorry if you took my comment about the old make file being "incomprehensible". It was not directed at you personally.
Re: some of things you pointed out:
> 1. The "all*" tasks use recursive make -e to override variables. I've never had to use that feature before. It makes it very hard to figure out what's going to happen.   

This was the only way I could retain the value of `ONT_IDS` to work with the big vs small onts.

> 2. The "all" tasks run "db" to build dashboard/index.html before running the ontology tasks. After running make clean these seemed to run the whole build twice.  

I'm not sure, if it runs twice ... I'd have to check.

> .PHONY: dashboard/index.html should not be used with a file -- files aren't PHONY.   

Yes. That was a mistake. Not sure how it ended up there. Thanks for catching this.

> I've never had to use a conditional like this in a Makefile, I would just use a script.   

Yes. This logic can be used in a script. For now I was just wanting to get it running.

cc @cmungall

**Comment by ddooley** [comment]
I can echo that my experience in deciphering what the Makefile does was very slow, and when I come back to revisit it every year or two I find that I have to reeducate myself as though I were learning perl.  It seems to me though to contemplate an alternative, like a more readable 100% python script that has the same capability, would require buy-in, and funding.

**Comment by jamesaoverton** [comment]
@ddooley: The key advantage of a Makefile over a Python script is that Make will calculate the graph of dependencies among tasks and build only what needs to be built. While Make supports a lot of bells and whistles, by sticking to a small subset of features you can gain the key benefits of Make without the obscurity of Perl. That's the spirit behind my review of this PR.

**Comment by wdduncan** [comment]
@jamesaoverton I agree with spirit of what you said. But, IMHO, the original makefile has become way too complicated. I spent days (much to Chris' dismay) trying to follow what was going on, and finally just decided I had to redo it.

In my next iteration (assuming there is one), I going to look into more places where judicious use of python scripts might to make the logic more straightforward. Just not sure when I'll get around to this though.

**Comment by jamesaoverton** [comment]
@wdduncan Yes. The first thing I said in my review was that the current Makefile isn't very friendly, and that I understand why you would want to revise it. But the new file is 50% longer, adds the complexity of recursion with `-e` with a conditional macro, has an expensive bug, and some other smaller problems. Now I'm just repeating myself, so I'll bow out of this conversation.

**Comment by wdduncan** [comment]
@jamesaoverton Sorry you are bowing out of thread. I thought it was productive.
This PR was not intended to be the final product. That is why I requested you to review. But, if yo prefer not to review, I understand.

As for other points:
- I think the ifneq logic is easier to follow than what was in the original. Plus, as mentioned, more logic can be placed in a script.
- Not sure how much the length matters. Compact/terse programs can be much more difficult to mantain and debut. Many perl programs are great examples of this. But, I guess that boils down to taste and expertise, and willingness to maintain that expertise.
- Without stats, I do not know how expensive the "bug" is, or even if it is one.

I'm sure, I am pretty sure I'll be working on this again. So, this is by no means the final product.

Sorry to see you "bow out".

**Comment by wdduncan** [comment]
Should we close this PR? It seems dead now.

**Comment by jamesaoverton** [comment]
Ok, I'll close it.

**Pull request closed without merging**
