### PR TITLE
Add more careful check for version IRIs

### PR DESCRIPTION
**Pull request by cthoyt**
Closes https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2370

This PR adds a check that a version IRI contains exactly one of:

1. A semantic version (see https://semver.org for exaplanation of semantic versioning, regex ideas from https://gist.github.com/jhorsman/62eeea161a13b80e39f5249281e17c39)
2. An ISO 8601-compliant date (e.g., no american or european nonsense)

Depends on:

- [x] https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1921

### CODE REVIEW

**Comment by cthoyt** [comment]
The implementation now works as expected and passes unit tests

**Comment by matentzn** [comment]
- [ ] Depends on https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1921

**Comment by anitacaron** [comment]
@matentzn, can I merge this PR?

**Comment by matentzn** [comment]
I have not tested this, but if you @anitacaron are happy to test it (merge and then fix if there are problems) I am happy with this!

**Comment by cthoyt** [comment]
There are unit tests in the PR. this doesn't fully address all possible false positives, but it's an excellent step forwards to catch the kind of issues e.g., that the fraunhofer group has had, that leads to an ineffective use of reviewer time

**Comment by cthoyt** [comment]
@anitacaron can we please merge this

**Comment by anitacaron** [comment]
I still need to test. I'll make some time this week.

**Review by anitacaron — APPROVED** [review]

**Pull request merged**
