### PR TITLE
Fixes syntax check

### LINKED ISSUE #50: Ontologies pass common format because of pre-processing
According to the [metrics](http://dashboard.obofoundry.org/dashboard/analysis.html), there are still 4 ontologies not exporting in a standard format:

```
OWL/XML Syntax             2
OWL Functional Syntax      1
unknown                    1
```

These don't show up on the dashboard though, because of the base-file extraction process preceding the metrics pipeline. Easy fix by using raw file for testing common format principle rather than base.

### PR DESCRIPTION
**Pull request by matentzn**
Fixes #50, #42

Previously, the syntax check was done on the preprocessed file, which is by default RDF/XML. This changes the check to the raw file.

### CODE REVIEW

**Review by jamesaoverton — APPROVED** [review]

**Comment by cthoyt** [comment]
@matentzn note that #42 wasn't automatically closed because you didn't write out "fixes" twice

**Comment by matentzn** [comment]
I am not going to ask @cthoyt how on earth you went through the trouble of asserting that.

**Comment by cthoyt** [comment]
I get notifications for all activities on OBO Foundry. I happen to have run into this issue before so I knew to let you know (imagine how much person-time it will take to go clean up all of the accidentally unclosed issues on OBO Foundry...)

**Comment by matentzn** [comment]
You are nuts man. I have unfollowed all notifications of all projects including the ones I work on...

**Pull request merged**
