### PR TITLE
feat: export dashboard results in JSON

### PR DESCRIPTION
**Pull request by jsstevenson**
(In addition to existing YAML output.) 

JSON can be parsed natively by Javascript runtimes so it's easier for other client-facing services (eg the central obofoundry table) to consume.

***I don't really know if this is the correct place to insert this into the workflow, and wasn't able to get a run going to test it yesterday, but wanted to put this PR up to hopefully get the ball rolling anyway. The only important thing is to remember to pass a custom function to `json.dump` to serialize the datetime objects.

would resolve https://github.com/OBOFoundry/obo-dash.github.io/issues/16

### CODE REVIEW

**Comment by matentzn** [comment]
Why not add the dumping code here; https://github.com/OBOFoundry/OBO-Dashboard/blob/0af8ac6da43e6607c9a1eecb52a820d00438abca/util/dashboard_config.py#L457?

**Comment by jsstevenson** [comment]
@matentzn you'd know better than I would, but that looked to me like it's within a loop that goes through each individual ontology (the `ont_results_path` variable there is `dashboard/<ontology name>/dashboard.yml`) and I think we'd want a single file that consumers could just request once? (for that matter, all I really need is the `namespace` and `summary` properties within each item that's listed under `ontologies:`)

**Comment by matentzn** [comment]
I think add here: https://github.com/OBOFoundry/OBO-Dashboard/blob/fb5464e56cdede37ca5da2f3fb914208d766a6ed/util/create_dashboard_html.py#L92C15-L92C35

**Comment by anitacaron** [comment]
@jsstevenson I only noticed now that your first commit, which you reverted, was a good solution. I've cleaned the PR for you.

**Review by anitacaron — APPROVED** [review]

**Comment by jsstevenson** [comment]
Cool, thanks @anitacaron! I don't remember why I ended up reverting it but if it works for y'all, then great!

**Review by matentzn — APPROVED** [review]
Awesome!

**Pull request merged**
